# Generated by Django 2.0.7 on 2019-01-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_attachment_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
