# Generated by Django 2.0.7 on 2019-01-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_attachment_upload', '0002_attachment_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
